apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  volumes:
    - name: dbconfig # docker volume create dbconfig
      configMap:
        name: database
        optional: true # mark the variable as optional
  containers:
  - image: nginx
    name: nginx
    volumeMounts: # docker run -v dbconfig:/etc/foo
    - name: dbconfig
      mountPath: "/etc/nginx"
      readOnly: true
