# Opaque is the default Secret type
apiVersion: v1
kind: Secret
metadata:
  name: dummy
data:
  password: dG9wc2VjcmV0 # base64 encoded value
  username: c2hhYmJpcg== # base64 encoded value
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: dummy
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: dummy
      optional: true
